#!/usr/bin/env python3
"""
render_grants_template.py
-------------------------
Renders the Unity Catalog GRANT statements for the Customer Health Command Center
with the actual Databricks App service principal client ID substituted in.

Usage:
    python scripts/render_grants_template.py <APP_SERVICE_PRINCIPAL_CLIENT_ID>

Example:
    python scripts/render_grants_template.py 1234567890abcdef

Where to find the service principal client ID:
    Databricks workspace → Apps → [your app] → [view permissions or settings]
    The client ID is the UUID-style identifier associated with the app's
    managed service principal.

Note on SQL warehouse permissions:
    CAN USE on the SQL warehouse cannot be granted via SQL DDL.
    After running the output below, also grant warehouse access through:
      - Databricks UI: SQL Warehouses → [warehouse] → Permissions →
          Add [service principal] with "Can use"
      - OR via the Databricks REST API:
          PATCH /api/2.0/permissions/warehouses/<warehouse_id>
"""

import sys

# ---------------------------------------------------------------------------
# Catalog and table constants — must match the pipeline notebooks
# ---------------------------------------------------------------------------

CATALOG = "dn_saas_demo"

GOLD_TABLES = [
    f"{CATALOG}.gold.gold_account_health",
    f"{CATALOG}.gold.gold_exec_kpis",
    f"{CATALOG}.gold.gold_risk_segments",
]


def render(sp_client_id: str) -> str:
    lines = [
        "-- ================================================================",
        "-- Unity Catalog GRANT Statements",
        f"-- Catalog    : {CATALOG}",
        f"-- Principal  : {sp_client_id}",
        "-- Generated by: scripts/render_grants_template.py",
        "-- ================================================================",
        "",
        "-- 1. Catalog access",
        f"GRANT USE CATALOG ON CATALOG {CATALOG}",
        f"  TO `{sp_client_id}`;",
        "",
        "-- 2. Schema access (all three layers, though app reads gold only)",
        f"GRANT USE SCHEMA ON SCHEMA {CATALOG}.bronze",
        f"  TO `{sp_client_id}`;",
        "",
        f"GRANT USE SCHEMA ON SCHEMA {CATALOG}.silver",
        f"  TO `{sp_client_id}`;",
        "",
        f"GRANT USE SCHEMA ON SCHEMA {CATALOG}.gold",
        f"  TO `{sp_client_id}`;",
        "",
        "-- 3. Table-level SELECT on app-facing gold tables",
    ]

    for table in GOLD_TABLES:
        lines.append(f"GRANT SELECT ON TABLE {table}")
        lines.append(f"  TO `{sp_client_id}`;")
        lines.append("")

    lines += [
        "-- ================================================================",
        "-- SQL WAREHOUSE PERMISSION (not SQL-grantable)",
        "-- ================================================================",
        "-- Grant CAN USE on the SQL warehouse through the Databricks UI:",
        "--   SQL Warehouses → [your warehouse] → Permissions",
        f"--   Add service principal [{sp_client_id}] with 'Can use' permission",
        "--",
        "-- Or via REST API:",
        "--   PATCH /api/2.0/permissions/warehouses/<warehouse_id>",
        "--   Body: { \"access_control_list\": [",
        f'--     {{ "service_principal_name": "{sp_client_id}",',
        '--       "permission_level": "CAN_USE" }] }',
        "",
        "-- ================================================================",
        "-- Validation — run these after applying grants",
        "-- ================================================================",
        f"-- SHOW GRANTS ON CATALOG {CATALOG};",
        f"-- SHOW GRANTS ON SCHEMA {CATALOG}.gold;",
    ]
    for table in GOLD_TABLES:
        lines.append(f"-- SHOW GRANTS ON TABLE {table};")

    return "\n".join(lines)


def main():
    if len(sys.argv) != 2:
        print(__doc__)
        print("ERROR: Provide exactly one argument: the service principal client ID.")
        sys.exit(1)

    sp_id = sys.argv[1].strip()
    if not sp_id:
        print("ERROR: Service principal client ID cannot be empty.")
        sys.exit(1)

    print(render(sp_id))


if __name__ == "__main__":
    main()
